version: '3'

tasks:
  install:
    desc: Install all dependencies (including dev)
    cmds:
      - python3 -m venv .venv
      - . .venv/bin/activate && pip install --upgrade pip
      - . .venv/bin/activate && pip install -e ".[dev]"
      - . .venv/bin/activate && pip install build
    sources:
      - pyproject.toml
      - requirements.txt
    generates:
      - .venv

  test:
    desc: Run tests with coverage
    cmds:
      - . .venv/bin/activate && poetry run pytest --cov=tfsumpy --cov-report=term && poetry run coverage report --fail-under=80
    deps: [install]

  lint:
    desc: Run linting (pylint and mypy)
    cmds:
      - . .venv/bin/activate && pylint tfsumpy
      - . .venv/bin/activate && mypy tfsumpy
    deps: [install]

  build:
    desc: Build the package
    cmds:
      - . .venv/bin/activate && python -m build
    deps: [install] 

  run-check:
    desc: Run all checks (install, lint, test)
    cmds:    
      - poetry run ruff check .
    deps: [install]
